### ISSUE TITLE
Landing Page | Menu

### ISSUE THREAD

**Issue by mtuchi** [pycontanzania/website#1]
## Description
- [x] On the Menu, please update and change Schedule to **Timetable**

**Comment by decolnz** [comment]
- On the Menu, please update and change Schedule to **Timetable**
 
- 1st December shall be date of arrival, meet-up and registration. 
- 2nd December shall be date of workshops and tutorials
- 3rd December shall be date of Conference
- 4th December shall be the date for local Tour

**Comment by decolnz** [comment]
Please note that we will share details below by 22nd Nov 2021

1. Speakers Profile in terms of Title, Photos
2. Full Timetable for 2nd and 3rd December
