### ISSUE TITLE
New Page for Gallery Section

### ISSUE THREAD

**Issue by Davisy** [pycontanzania/website#13]
I just recommend having a new page on the website that shows gallery sections of photos from different pycon events. You can check this site as a demo http://www.kijichilutheranchurch.or.tz/picha

**Comment by mtuchi** [comment]
> I just recommend having a new page on the website that shows gallery sections of photos from different pycon events. You can check this site as a demo http://www.kijichilutheranchurch.or.tz/picha

More pictures more loading time more optimization for better speed, the website should serve the purpose of being an information place for Pycon Tanzania

However there is a possibility of using PyCon Tanzania Instagram page for gallery section

**Comment by Davisy** [comment]
Yeah, you are correct, we can go with your idea of using the Pycon Tanzania Instagram page.
