### ISSUE TITLE
Timetable

### ISSUE THREAD

**Issue by decolnz** [pycontanzania/website#3]
## Description
- [x] 1st December shall be date of arrival, meet-up and registration. 
- [x] 2nd December shall be date of workshops and tutorials
- [x] 3rd December shall be date of Conference
- [x] 4th December shall be the date for local Tour  

**Timetable for 1st December 2021**

**Pre Morning Session**
08.00 Registration
09:00 - 12:00 Py Meetups

**Comment by decolnz** [comment]
**Timetable for 2nd December 2021**


Morning Session 
Antony Mipawa - JUNIOR DATA SCIENTIST
Catherine Alex - UnderGrad Student
Isack Odero - Electrical Engineer

Afternoon Session 
Neema Rajabu - ASSISTANT LECTURER
Eliya Masesa - BlockChain Developer
Zephania Reuben - Software Engineer

Evening Session
Mary Isamba - CYBER SECURITY CONSULTANT
Juan Pablo Maldonado - INDEPENDENT TRAINER & CONSULTANT
Martha Kamkuemah - GRADUATE STUDENT

3rd Dec 2021 - Closing Guest of Honour
Prof. Eliamani Sedayoke

**Comment by decolnz** [comment]
**Timetable for 3rd December 2021**


Pre Morning Session
-----------------------
08:00 Arrival and Registration 
09.00 Noah CONVENER

**Morning Session**
09:00 Antony Mipawa - JUNIOR DATA SCIENTIST
09:30 Catherine Alex - UNDERGRAD STUDENT
10:00 Isack Odero - ELECTRICAL ENGINEER

10:30 **BREAK**

**Afternoon Session**
11:00 Neema Rajabu - ASSISTANT LECTURER
11:30 Eliya Masesa - BLOCKCHAIN DEVELOPER
12:00 Mary Isamba - CYBER SECURITY CONSULTANT 
12:30 Leticia Nkulu - SOFTWARE DEVELOPER 

13:00 **LUNCH**

**Evening Session**
14:00 Martha Kamkuemah - GRADUATE STUDENT
14:30 Juan Pablo Maldonado - INDEPENDENT TRAINER & CONSULTANT
15:00 Zephania Reuben - SOFTWARE ENGINEER
15:30 Panel Discussion 
16:00 Prof. Eliamani Sedayoke - Guest of Honour

**Comment by decolnz** [comment]
Pablo wont make it and we will need to remove him from speakers and replace him with Mustafa Saifuddin who will present **Interacting with BEEM API's**

**Comment by mtuchi** [comment]
This is fixed 👉🏽 d442b97
