### ISSUE TITLE
Speakers Profile and Photos

### ISSUE THREAD

**Issue by decolnz** [pycontanzania/website#5]
Please find the names and titles of speakers who have already shared their photos which are attached. 

1. Mary Isamba - CYBER SECURITY CONSULTANT
2. Neema Rajabu - ASSISTANT LECTURER 
3. Juan Pablo Maldonado - INDEPENDENT TRAINER & CONSULTANT
4. Martha Kamkuemah - GRADUATE STUDENT
5. Antony Mipawa - JUNIOR DATA SCIENTIST
6. Eliya Masesa - BlockChain Developer
7. Zephania Reuben - Software Engineer
8. Catherine Alex - UnderGrad Student 
9. Isack Odero - Electrical Engineer 
10. Lusajo Shitindi - BlockChain Developer
11. Prof. Eliamani Sedayoke  - Guest of Honour

**Comment by decolnz** [comment]
Please find the names and titles of speakers who have already shared their photos which are attached. 

1. Mary Isamba - CYBER SECURITY CONSULTANT
2. Neema Rajabu - ASSISTANT LECTURER 
3. Juan Pablo Maldonado - INDEPENDENT TRAINER & CONSULTANT
4. Martha Kamkuemah - GRADUATE STUDENT
5. Antony Mipawa - JUNIOR DATA SCIENTIST
6. Eliya Masesa - BlockChain Developer
7. Zephania Reuben - Software Engineer
8. Catherine Alex - UnderGrad Student 
9. Isack Odero - Electrical Engineer 
10. Prof. Eliamani Sedayoke  - Guest of Honour
[PyCon Speakers 2021.zip](https://github.com/pycontanzania/website/files/7576872/PyCon.Speakers.2021.zip)

**Comment by mtuchi** [comment]
This was done
Opening another issue for **Leticia Nkulu** - Ujuzi Forum - Ada Lovelace #11
